server:
  port: 8085

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: event-reminder
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/event_reminder}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      auto-commit: false
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 15
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        query:
          fail_on_pagination_over_collection_fetch: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mail:
    host: ${MAIL_HOST:smtp.mail.ru}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: ${MAIL_PORT:465}
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  thymeleaf:
    cache: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
  health:
    mail:
      enabled: false
  info:
    git:
      mode: full

app:
  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN:}
  mail:
    from: ${MAIL_FROM:noreply@event-reminder.app}
  scheduler:
    cron: "0 * * * * *"
    start-of-day-hour: 9
